// src/components/Header.svelte
<script>
  let isMenuOpen = false;
  let isScrolled = false;

  function checkScrollState() {
    isScrolled = window.scrollY > 0;
  }
  document.addEventListener("scroll", checkScrollState);
  checkScrollState();

  let togglingMenu = false;
  function setMenuOpen(value) {
    if (togglingMenu) return;
    togglingMenu = true;
    isMenuOpen = value;
    setTimeout(() => (togglingMenu = false), 150);
  }
  function toggleMenu() {
    setMenuOpen(!isMenuOpen);
  }
</script>

<header
  class={isMenuOpen
    ? "fixed flex justify-center w-full top-0 z-10 p-0 bg-gradient-to-b from-neutral-900 from-20% to-transparent select-none transition-all"
    : isScrolled
    ? "fixed flex justify-center w-full top-0 z-10 py-5 bg-gradient-to-b from-neutral-900 from-20% to-transparent select-none transition-all"
    : "fixed flex justify-center w-full top-0 z-10 py-5 sm:py-5 bg-gradient-to-b from-neutral-900 from-20% to-transparent select-none transition-all"}
>
  <div class="container touch-none">
    <nav
      id="nav"
      class={isMenuOpen
        ? "mx-0 p-10 rounded-none border border-transparent flex items-center backdrop-blur bg-neutral-900/100 shadow transition-all flex-col sm:flex-row gap-10 h-screen sm:h-auto"
        : isScrolled
        ? "mx-5 py-5 px-5 rounded-lg border border-zinc-700/50 flex justify-between items-center backdrop-blur bg-neutral-900/80 shadow transition-all flex-col sm:flex-row gap-5 h-[4.375rem] sm:h-auto"
        : "mx-5 py-5 px-0 rounded-lg border border-transparent flex justify-between items-center backdrop-blur-none bg-transparent shadow-none transition-all flex-col sm:flex-row gap-5 h-[4.375rem] sm:h-auto"}
    >
      <div class="flex justify-between items-center w-full">
        <a
          href="/#"
          class="opacity-80 hover:opacity-100 transition"
          on:click={() => setMenuOpen(false)}
        >
          <img src="/img/brand/logo.svg" alt="Logo" class="h-7 mx-1" />
        </a>
        <button id="menu-button" aria-label="Menu" on:click={() => toggleMenu()}>
          {#if isMenuOpen}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              height="1.5em"
              class="fill-current text-white/75 hover:text-white transition cursor-pointer sm:hidden mx-1"
              viewBox="0 0 384 512"
              ><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path
                d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"
              /></svg
            >
          {:else}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              height="1.2em"
              viewBox="0 0 448 512"
              class="fill-current text-white/75 hover:text-white transition cursor-pointer sm:hidden mx-1"
              ><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
              <path
                d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"
              /></svg
            >
          {/if}
        </button>
      </div>
      <div
        id="menu-container"
        class={isMenuOpen
          ? "sm:block opacity-100 w-full sm:w-min flex-grow flex"
          : "hidden sm:block opacity-0 sm:opacity-100 w-full sm:w-min"}
      >
        <menu class="flex gap-5 sm:gap-5 flex-col sm:flex-row">
          <li>
            <a
              href="#experience"
              class="flex items-center text-2xl sm:text-sm rounded sm:px-3 py-2 sm:uppercase text-white/75 sm:tracking-wider hover:text-white active:text-white sm:hover:bg-neutral-600/50 sm:hover:active:scale-95 transition"
              draggable="false"
              on:click={() => setMenuOpen(false)}
            >
              Experience
            </a>
          </li>
          <li>
            <a
              href="#skills"
              class="flex items-center text-2xl sm:text-sm rounded sm:px-3 py-2 sm:uppercase text-white/75 sm:tracking-wider hover:text-white active:text-white sm:hover:bg-neutral-600/50 sm:hover:active:scale-95 transition"
              draggable="false"
              on:click={() => setMenuOpen(false)}
            >
              Skills
            </a>
          </li>
          <li>
            <a
              href="#portfolio"
              class="flex items-center text-2xl sm:text-sm rounded sm:px-3 py-2 sm:uppercase text-white/75 sm:tracking-wider hover:text-white active:text-white sm:hover:bg-neutral-600/50 sm:hover:active:scale-95 transition"
              draggable="false"
              on:click={() => setMenuOpen(false)}
            >
              Portfolio
            </a>
          </li>
          <li>
            <a
              href="#contact"
              class="flex items-center text-2xl sm:text-sm rounded sm:px-3 py-2 sm:uppercase text-white/75 sm:tracking-wider hover:text-white active:text-white sm:hover:bg-neutral-600/50 sm:hover:active:scale-95 transition"
              draggable="false"
              on:click={() => setMenuOpen(false)}
            >
              Contact
            </a>
          </li>
        </menu>
      </div>
    </nav>
  </div>
</header>

// app/_components/Header.tsx
import Image from "next/image";
import Link from "next/link";

import logo from "../../public/logo.svg";
import { MutableRefObject, useEffect, useState } from "react";
import { outfit } from "@/app/fonts";

export default function Header({
  observableRef,
}: {
  observableRef: MutableRefObject<any>;
}) {
  const [isScrolled, setIsScrolled] = useState<boolean>();

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        setIsScrolled(!entry.isIntersecting);
      },
      {
        root: null,
        threshold: 1,
      },
    );

    observer.observe(observableRef.current);

    return () => observer.disconnect();
  }, [observableRef]);

  return (
    <header className="fixed top-2.5 z-20 w-full">
      <div className="mx-auto max-w-screen-xl px-5">
        <div
          className={`${
            isScrolled
              ? "bg-neutral-300/75 px-3 backdrop-blur-lg dark:bg-neutral-900/75"
              : ""
          } flex items-center justify-between rounded-2xl py-3 transition-all`}
        >
          <Link
            href="/"
            className={`${
              isScrolled ? "mx-2" : "mr-2"
            } opacity-70 transition-all hover:opacity-100 focus:opacity-100 active:hover:scale-90`}
          >
            <Image alt="Logo" src={logo} className="h-5 w-auto dark:invert" />
          </Link>
          <nav>
            <ul className="flex gap-2 overflow-hidden">
              <NavLink href="#skills">Skills</NavLink>
              <NavLink href="#projects">Projects</NavLink>
              <NavLink href="#experience">Experience</NavLink>
              <NavLink href="#contact">Contact</NavLink>
            </ul>
          </nav>
        </div>
      </div>
    </header>
  );
}

function NavLink({
  children,
  href,
}: {
  children: React.ReactNode;
  href: string;
}) {
  return (
    <li>
      <Link
        href={href}
        className={`${outfit.className} block rounded-lg px-3 py-2 text-sm uppercase tracking-wider transition hover:bg-neutral-300/50 focus:bg-neutral-300/50 focus:outline-none active:hover:scale-90 dark:hover:bg-neutral-800/75 dark:focus:bg-neutral-800/75`}
      >
        {children}
      </Link>
    </li>
  );
}
